name: Build
on: workflow_dispatch
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Build
        run: |
          chmod +x gradlew
          echo VERSION=$(./gradlew -q properties | grep 'version:' | cut -d ' ' -f 2) >> $GITHUB_ENV
          ./gradlew build

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/libs/*.jar
          tag_name: v${{ env.VERSION }}
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}